import { createActionTypes } from '../utils'

export const REST_API = createActionTypes('REST_API', [
  'GET',
  'GET_ONE',
  'SAVE',
  'PUT',
  'PATCH',
  'DELETE',
  'SUCCESS',
  'FAILURE',
])

export const DS160 = createActionTypes('DS160', [
  'DS160_INIT_STATE',
  'DS160_NEXT_STEP',
  'DS160_PREV_STEP',
  'DS160_UPDATE_VALUES',
  'DS160_SAVE_REQUEST',
  'DS160_SAVE_SUCCESS',
  'DS160_SAVE_FAILURE',
  'DS160_GET_REQUEST',
  'DS160_GET_SUCCESS',
  'DS160_GET_FAILURE',
  'DS160_CHECKOUT_REQUEST',
  'DS160_CHECKOUT_SUCCESS',
  'DS160_CHECKOUT_FAILURE',
  'RESET_CHECKOUT_RESULT'
])

export const ADMIN = createActionTypes('ADMIN', [
  'RESET',
  'GET_CUSTOMER_LIST_REQUEST',
  'GET_CUSTOMER_LIST_SUCCESS',
  'GET_CUSTOMER_LIST_FAILURE',
  'SET_PAGINATION',
  'GET_MAIL_TEMPATES_LIST_REQUEST',
  'GET_MAIL_TEMPATES_LIST_SUCCESS',
  'GET_MAIL_TEMPATES_LIST_FAILURE',
  'CREATE_MAIL_TEMPLATE_REQUEST',
  'CREATE_MAIL_TEMPLATE_SUCCESS',
  'CREATE_MAIL_TEMPLATE_FAILURE',
  'HIDE_MODAL',
  'SHOW_MODAL',
  'DELETE_MAIL_TEMPLATE_REQUEST',
  'DELETE_MAIL_TEMPLATE_SUCCESS',
  'DELETE_MAIL_TEMPLATE_FAILURE',
  'UPDATE_MAIL_TEMPLATE_REQUEST',
  'UPDATE_MAIL_TEMPLATE_SUCCESS',
  'UPDATE_MAIL_TEMPLATE_FAILURE',
  'LOGIN_REQUEST',
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',
  'RESEND_EMAIL_REQUEST',
  'RESEND_EMAIL_SUCCESS',
  'RESEND_EMAIL_FAILURE',
])

export default {
  REST_API,
  DS160,
  ADMIN
}
