import React from "react";

// export const myURL = 'http://localhost:3000'
// export const apiURL = 'http://localhost:4040/api/'
export const myURL = 'http://3.16.123.4'
export const apiURL = 'http://3.16.123.4/v1/api/'

export const export_list = (array) => {
    return array.map(option => {
        return {
            value: option.props.value,
            label: option.props.children
        }
    })
}

export const occupation_options = [
    <option value="A">AGRICULTURE</option>,
    <option value="AP">ARTIST/PERFORMER</option>,
    <option value="B">BUSINESS</option>,
    <option value="CM">COMMUNICATIONS</option>,
    <option value="CS">COMPUTER SCIENCE</option>,
    <option value="C">CULINARY/FOOD SERVICES</option>,
    <option value="ED">EDUCATION</option>,
    <option value="EN">ENGINEERING</option>,
    <option value="G">GOVERNMENT</option>,
    <option value="H">HOMEMAKER</option>,
    <option value="LP">LEGAL PROFESSION</option>,
    <option value="MH">MEDICAL/HEALTH</option>,
    <option value="M">MILITARY</option>,
    <option value="NS">NATURAL SCIENCE</option>,
    <option value="N">NOT EMPLOYED</option>,
    <option value="PS">PHYSICAL SCIENCES</option>,
    <option value="RV">RELIGIOUS VOCATION</option>,
    <option value="R">RESEARCH</option>,
    <option value="RT">RETIRED</option>,
    <option value="SS">SOCIAL SCIENCE</option>,
    <option value="S">STUDENT</option>,
    <option value="O">OTHER</option>,
]

export const US_Live_Status = [
	<option value="S">U.S. CITIZEN</option>,
	<option value="C">U.S. LEGAL PERMANENT RESIDENT (LPR)</option>,
	<option value="P">NONIMMIGRANT</option>,
	<option value="O">OTHER/I DON'T KNOW</option>,
]

export const relative_relationship_options = [
    <option value="S">SPOUSE</option>,
    <option value="F">FIANCÉ/FIANCÉE</option>,
    <option value="C">CHILD</option>,
    <option value="B">SIBLING</option>,
]

export const relationship_options = [
	<option value="R">RELATIVE</option>,
	<option value="S">SPOUSE</option>,
	<option value="C">FRIEND</option>,
	<option value="B">BUSINESS ASSOCIATE</option>,
	<option value="P">EMPLOYER</option>,
	<option value="H">SCHOOL OFFICIAL</option>,
	<option value="O">OTHER</option>
]

export const passport_type_options = [
    <option value="R">REGULAR</option>,
    <option value="O">OFFICIAL</option>,
    <option value="D">DIPLOMATIC</option>,
    <option value="L">LAISSEZ-PASSER</option>,
    <option value="T">OTHER</option>,
]

export const social_media_options = [
    <option value="ASKF">ASK.FM</option>,
    <option value="DUBN">DOUBAN</option>,
    <option value="FCBK">FACEBOOK</option>,
    <option value="FLKR">FLICKR</option>,
    <option value="GOGL">GOOGLE+</option>,
    <option value="INST">INSTAGRAM</option>,
    <option value="LINK">LINKEDIN</option>,
    <option value="MYSP">MYSPACE</option>,
    <option value="PTST">PINTEREST</option>,
    <option value="QZNE">QZONE (QQ)</option>,
    <option value="RDDT">REDDIT</option>,
    <option value="SWBO">SINA WEIBO</option>,
    <option value="TWBO">TENCENT WEIBO</option>,
    <option value="TUMB">TUMBLR</option>,
    <option value="TWIT">TWITTER</option>,
    <option value="TWOO">TWOO</option>,
    <option value="VINE">VINE</option>,
    <option value="VKON">VKONTAKTE (VK)</option>,
    <option value="YUKU">YOUKU</option>,
    <option value="YTUB">YOUTUBE</option>,
    <option value="NONE">NONE</option>,
]

export const state_options_list = () => {
    return export_list(state_options)
}

export const state_options = [
        <option value="AL">ALABAMA</option>,
        <option value="AK">ALASKA</option>,
        <option value="AS">AMERICAN SAMOA</option>,
        <option value="AZ">ARIZONA</option>,
        <option value="AR">ARKANSAS</option>,
        <option value="CA">CALIFORNIA</option>,
        <option value="CO">COLORADO</option>,
        <option value="CT">CONNECTICUT</option>,
        <option value="DE">DELAWARE</option>,
        <option value="DC">DISTRICT OF COLUMBIA</option>,
        <option value="FL">FLORIDA</option>,
        <option value="GA">GEORGIA</option>,
        <option value="GU">GUAM</option>,
        <option value="HI">HAWAII</option>,
        <option value="ID">IDAHO</option>,
        <option value="IL">ILLINOIS</option>,
        <option value="IN">INDIANA</option>,
        <option value="IA">IOWA</option>,
        <option value="KS">KANSAS</option>,
        <option value="KY">KENTUCKY</option>,
        <option value="LA">LOUISIANA</option>,
        <option value="ME">MAINE</option>,
        <option value="MD">MARYLAND</option>,
        <option value="MA">MASSACHUSETTS</option>,
        <option value="MI">MICHIGAN</option>,
        <option value="MN">MINNESOTA</option>,
        <option value="MS">MISSISSIPPI</option>,
        <option value="MO">MISSOURI</option>,
        <option value="MT">MONTANA</option>,
        <option value="NE">NEBRASKA</option>,
        <option value="NV">NEVADA</option>,
        <option value="NH">NEW HAMPSHIRE</option>,
        <option value="NJ">NEW JERSEY</option>,
        <option value="NM">NEW MEXICO</option>,
        <option value="NY">NEW YORK</option>,
        <option value="NC">NORTH CAROLINA</option>,
        <option value="ND">NORTH DAKOTA</option>,
        <option value="MP">NORTHERN MARIANA ISLANDS</option>,
        <option value="OH">OHIO</option>,
        <option value="OK">OKLAHOMA</option>,
        <option value="OR">OREGON</option>,
        <option value="PA">PENNSYLVANIA</option>,
        <option value="PR">PUERTO RICO</option>,
        <option value="RI">RHODE ISLAND</option>,
        <option value="SC">SOUTH CAROLINA</option>,
        <option value="SD">SOUTH DAKOTA</option>,
        <option value="TN">TENNESSEE</option>,
        <option value="TX">TEXAS</option>,
        <option value="UT">UTAH</option>,
        <option value="VT">VERMONT</option>,
        <option value="VI">VIRGIN ISLANDS</option>,
        <option value="VA">VIRGINIA</option>,
        <option value="WA">WASHINGTON</option>,
        <option value="WV">WEST VIRGINIA</option>,
        <option value="WI">WISCONSIN</option>,
        <option value="WY">WYOMING</option>,
]

export const person_travel_with_relationship_options = [
    { value: 'P', label: 'PARENT'},
    { value: 'S', label: 'SPOUSE'},
    { value: 'C', label: 'CHILD'},
    { value: 'R', label: 'OTHER RELATIVE'},
    { value: 'F', label: 'FRIEND'},
    { value: 'B', label: 'BUSINESS ASSOCIATE'},
    { value: 'O', label: 'OTHER'},
]

export const paying_person_info_relationship_options = [
    { value: 'C', label: 'CHILD'},
    { value: 'P', label: 'PARENT'},
    { value: 'S', label: 'SPOUSE'},
    { value: 'R', label: 'OTHER RELATIVE'},
    { value: 'F', label: 'FRIEND'},
    { value: 'O', label: 'OTHER'},
]

export const paying_person_for_trip_options = [
    { value: 'S', label: 'Self' },
    { value: 'O', label: 'Other Person' },
    { value: 'C', label: 'Other Company/Organization' },
]

export const period_unit_options = [
    { value: 'Y', label: 'YEAR(S)' },
    { value: 'M', label: 'MONTH(S)' },
    { value: 'W', label: 'WEEK(S)' },
    { value: 'D', label: 'DAY(S)' },
]

export const nationality_option_list_func = () => {
    return export_list(nationality_option_list)
}

export const purpose_of_trip_advanced_options_func = () => {
    return export_list(purpose_of_trip_advanced_options)
}

export const purpose_of_trip_advanced_options = [
    <option value="B">TEMP. BUSINESS PLEASURE VISITOR (B)</option>,
    <option value="C">ALIEN IN TRANSIT (C)</option>,
    <option value="D">CREWMEMBER (D)</option>,
    <option value="F">ACADEMIC OR LANGUAGE STUDENT (F)</option>,
    <option value="H">TEMPORARY WORKER (H)</option>,
    <option value="I">FOREIGN MEDIA REPRESENTATIVE (I)</option>,
    <option value="J">EXCHANGE VISITOR (J)</option>,
    <option value="L">INTRACOMPANY TRANSFEREE (L)</option>,
    <option value="M">VOCATIONAL/NONACADEMIC STUDENT (M)</option>,
]

export const purpose_of_trip_advanced_specify_options_func = (field) => {
    return export_list(purpose_of_trip_advanced_specify_options[field])
}

export const purpose_of_trip_advanced_specify_options = {
    'B': [
			<option value="B1-B2">BUSINESS &amp; TOURISM (TEMPORARY VISITOR) (B1/B2)</option>,
			<option value="B1-CF">BUSINESS/CONFERENCE (B1)</option>,
			<option value="B2-TM">TOURISM/MEDICAL TREATMENT (B2)</option>,
    ],
    'C': [
			<option value="C1-D">CREWMEMBER IN TRANSIT (C1/D)</option>,
			<option value="C1-TR">TRANSIT (C1)</option>,
			<option value="C2-UN">TRANSIT TO U.N. HEADQUARTERS (C2)</option>,
			<option value="C3-CH">CHILD OF A C3 (C3)</option>,
			<option value="C3-EM">PERSONAL EMP. OF A C3 (C3)</option>,
			<option value="C3-FR">FOREIGN OFFICIAL IN TRANSIT (C3)</option>,
			<option value="C3-SP">SPOUSE OF A C3 (C3)</option>,
    ],
    'D': [
			<option selected="selected" value="D-D">CREWMEMBER (D)</option>,
    ],
    'F': [
        <option value="F1-F1">STUDENT (F1)</option>,
        <option value="F2-CH">CHILD OF AN F1 (F2)</option>,
        <option value="F2-SP">SPOUSE OF AN F1 (F2)</option>,
    ],
    'H': [
        <option value="H1B-H1B">SPECIALTY OCCUPATION (H1B)</option>,
        <option value="H1B1-CHL">CHILEAN SPEC. OCCUPATION (H1B1)</option>,
        <option value="H1B1-SGP">SINGAPOREAN SPEC. OCCUPATION (H1B1)</option>,
        <option value="H1C-NR">NURSE IN SHORTAGE AREA (H1C)</option>,
        <option value="H2A-AG">AGRICULTURAL WORKER (H2A)</option>,
        <option value="H2B-NA">NONAGRICULTURAL WORKER (H2B)</option>,
        <option value="H3-TR">TRAINEE (H3)</option>,
        <option value="H4-CH">CHILD OF AN H (H4)</option>,
        <option value="H4-SP">SPOUSE OF AN H (H4)</option>,
    ],
    'I': [
        <option value="I-CH">CHILD OF AN I (I)</option>,
        <option value="I-FR">FOREIGN MEDIA REPRESENTATIVE (I)</option>,
        <option value="I-SP">SPOUSE OF AN I (I)</option>,
    ],
    'J': [
        <option value="J1-J1">EXCHANGE VISITOR (J1)</option>,
        <option value="J2-CH">CHILD OF A J1 (J2)</option>,
        <option value="J2-SP">SPOUSE OF A J1 (J2)</option>,
    ], 
    'L': [
        <option value="L1-L1">INTRACOMPANY TRANSFEREE (L1)</option>,
        <option value="L2-CH">CHILD OF A L1 (L2)</option>,
        <option value="L2-SP">SPOUSE OF A L1 (L2)</option>,
    ],
    'M': [
        <option value="M1-M1">STUDENT (M1)</option>,
        <option value="M2-CH">CHILD OF M1 (M2)</option>,
        <option value="M2-SP">SPOUSE OF M1 (M2)</option>,
        <option value="M3-M3">COMMUTER STUDENT (M3)</option>,
    ]
}
export const purpose_of_trip_advanced_specify_extra = {
    'B': {},
    'C': { 'C3-CH': 'N', 'C3-SP': 'N' },
    'D': {},
    'F': { 'F2-CH': 'N', 'F2-SP': 'N'},
    'H': { 'H1B-H1B': 'P', 'H1C-NR': 'P', 'H2A-AG': 'P', 'H2B-NA': 'P', 'H3-TR': 'P', 'H4-CH': 'NP', 'N4-SP': 'NP'},
    'I': { 'I-CH': 'N', 'I-SP': 'N'},
    'J': { 'J2-CH': 'N', 'J2-SP': 'N'},
    'L': { 'L1-L1': 'P', 'L2-CH': 'NP', 'L2-SP': 'NP'},
    'M': { 'M2-CH': 'N', 'M2-SP': 'N' }
}

export const day_options = [
    "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
    "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
    "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"
]

export const month_options = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]

export const martial_status_options = [
    { value: 'M', label: 'MARRIED' },
    { value: 'C', label: 'COMMON LAW MARRIAGE' },
    { value: 'P', label: 'CIVIL UNION/DOMESTIC PARTNERSHIP' },
    { value: 'S', label: 'SINGLE' },
    { value: 'W', label: 'WIDOWED' },
    { value: 'D', label: 'DIVORCED' },
    { value: 'L', label: 'LEGALLY SEPARATED' },
    { value: 'O', label: 'OTHER' },
]

export const purpose_of_trip_options = [
    { value: 'B', label: 'TEMP. BUSINESS PLEASURE VISITOR (B1/B2)' },
    { value: 'C', label: 'ALIEN IN TRANSIT (C)' },
    { value: 'D', label: 'CREWMEMBER (D)' },
    { value: 'F', label: 'ACADEMIC OR LANGUAGE STUDENT (F)' },
    { value: 'H', label: 'TEMPORARY WORKER (H)' },
    { value: 'I', label: 'FOREIGN MEDIA REPRESENTATIVE (I)' },
    { value: 'J', label: 'EXCHANGE VISITOR (J)' },
    { value: 'L', label: 'INTRACOMPANY TRANSFEREE (L)' },
    { value: 'M', label: 'VOCATIONAL/NONACADEMIC STUDENT (M)' }
]

export const countries_option_value_list = ["KBL", "TIA"
    , "ALG"
    , "LUA"
    , "BNS"
    , "YRV"
    , "MLB"
    , "PRT"
    , "SYD"
    , "VNN"
    , "BKU"
    , "NSS"
    , "MNA"
    , "DHK"
    , "BGN"
    , "MSK"
    , "BRS"
    , "BLZ"
    , "COT"
    , "HML"
    , "LPZ"
    , "SAR"
    , "GAB"
    , "BRA"
    , "PTA"
    , "RCF"
    , "RDJ"
    , "SPL"
    , "BSB"
    , "SOF"
    , "OUG"
    , "RNG"
    , "BUJ"
    , "PIA"
    , "PHP"
    , "YDE"
    , "CLG"
    , "HLF"
    , "MTL"
    , "OTT"
    , "QBC"
    , "TRT"
    , "VAC"
    , "NDJ"
    , "SNT"
    , "BEJ"
    , "CHE"
    , "GUZ"
    , "SHG"
    , "SNY"
    , "BGT"
    , "BRZ"
    , "KIN"
    , "SNJ"
    , "ABJ"
    , "ZGB"
    , "HAV"
    , "CRC"
    , "NCS"
    , "PRG"
    , "CPN"
    , "DJI"
    , "SDO"
    , "GYQ"
    , "QTO"
    , "CRO"
    , "SNS"
    , "LND"
    , "MBO"
    , "ASM"
    , "TAL"
    , "MBA"
    , "ADD"
    , "SUV"
    , "HLS"
    , "PRS"
    , "LIB"
    , "BAN"
    , "TBL"
    , "BRL"
    , "FRN"
    , "MUN"
    , "ACC"
    , "ATH"
    , "GTM"
    , "CRY"
    , "GEO"
    , "PTP"
    , "TGG"
    , "HNK"
    , "BDP"
    , "RKJ"
    , "MDR"
    , "HYD"
    , "CLC"
    , "BMB"
    , "NWD"
    , "JAK"
    , "SRB"
    , "BGH"
    , "ERB"
    , "DBL"
    , "TLV"
    , "FLR"
    , "MLN"
    , "NPL"
    , "RME"
    , "KNG"
    , "NHA"
    , "KBO"
    , "TKY"
    , "JRS"
    , "AMM"
    , "ATA"
    , "AST"
    , "NRB"
    , "PRI"
    , "KWT"
    , "BKK"
    , "VNT"
    , "RGA"
    , "BRT"
    , "MAS"
    , "MRV"
    , "VIL"
    , "LXM"
    , "SKO"
    , "ANT"
    , "LIL"
    , "KLL"
    , "BAM"
    , "VLL"
    , "MAJ"
    , "NUK"
    , "PTL"
    , "CDJ"
    , "GDL"
    , "HER"
    , "MTM"
    , "MER"
    , "MEX"
    , "MTR"
    , "NGL"
    , "NVL"
    , "TJT"
    , "KOL"
    , "CHS"
    , "ULN"
    , "POD"
    , "CSB"
    , "MAP"
    , "WHK"
    , "KDU"
    , "AMS"
    , "ACK"
    , "MNG"
    , "NMY"
    , "ABU"
    , "LGS"
    , "BLF"
    , "OSL"
    , "MST"
    , "ISL"
    , "KRC"
    , "KOR"
    , "PNM"
    , "PTM"
    , "ASN"
    , "LMA"
    , "MNL"
    , "KRK"
    , "WRW"
    , "LSB"
    , "DOH"
    , "BCH"
    , "MOS"
    , "VLA"
    , "YEK"
    , "KGL"
    , "APA"
    , "DHR"
    , "JDD"
    , "RID"
    , "DKR"
    , "BLG"
    , "FTN"
    , "SGP"
    , "BTS"
    , "LJU"
    , "CPT"
    , "DRB"
    , "JHN"
    , "SEO"
    , "JBA"
    , "MDD"
    , "CLM"
    , "KHT"
    , "PRM"
    , "STK"
    , "BEN"
    , "TAI"
    , "DHB"
    , "DRS"
    , "BNK"
    , "CHN"
    , "DIL"
    , "LOM"
    , "PTS"
    , "TNS"
    , "ANK"
    , "IST"
    , "AKD"
    , "KMP"
    , "KEV"
    , "ABD"
    , "DUB"
    , "MTV"
    , "THT"
    , "CRS"
    , "HAN"
    , "HCM"
    , "LUS"
    , "HRE"];
export const countries_option_label_list = [
    "AFGHANISTAN, KABUL",
    "ALBANIA, TIRANA",
    "ALGERIA, ALGIERS",
    "ANGOLA, LUANDA",
    "ARGENTINA, BUENOS AIRES",
    "ARMENIA, YEREVAN",
    "AUSTRALIA, MELBOURNE",
    "AUSTRALIA, PERTH",
    "AUSTRALIA, SYDNEY",
    "AUSTRIA, VIENNA",
    "AZERBAIJAN, BAKU",
    "BAHAMAS, NASSAU",
    "BAHRAIN, MANAMA",
    "BANGLADESH, DHAKA",
    "BARBADOS, BRIDGETOWN",
    "BELARUS, MINSK",
    "BELGIUM, BRUSSELS",
    "BELIZE, BELMOPAN",
    "BENIN, COTONOU",
    "BERMUDA, HAMILTON",
    "BOLIVIA, LA PAZ",
    "BOSNIA-HERZEGOVINA, SARAJEVO",
    "BOTSWANA, GABORONE",
    "BRAZIL, BRASILIA",
    "BRAZIL, PORTO ALEGRE",
    "BRAZIL, RECIFE",
    "BRAZIL, RIO DE JANEIRO",
    "BRAZIL, SAO PAULO",
    "BRUNEI, BANDAR SERI BEGAWAN",
    "BULGARIA, SOFIA",
    "BURKINA FASO, OUAGADOUGOU",
    "BURMA, RANGOON",
    "BURUNDI, BUJUMBURA",
    "CABO VERDE, PRAIA",
    "CAMBODIA, PHNOM PENH",
    "CAMEROON, YAOUNDE",
    "CANADA, CALGARY",
    "CANADA, HALIFAX",
    "CANADA, MONTREAL",
    "CANADA, OTTAWA",
    "CANADA, QUEBEC",
    "CANADA, TORONTO",
    "CANADA, VANCOUVER",
    "CHAD, N`DJAMENA",
    "CHILE, SANTIAGO",
    "CHINA, BEIJING",
    "CHINA, CHENGDU",
    "CHINA, GUANGZHOU",
    "CHINA, SHANGHAI",
    "CHINA, SHENYANG",
    "COLOMBIA, BOGOTA",
    "CONGO, BRAZZAVILLE",
    "CONGO, KINSHASA",
    "COSTA RICA, SAN JOSE",
    "COTE D`IVORIE, ABIDJAN",
    "CROATIA, ZAGREB",
    "CUBA, HAVANA",
    "CURACAO, CURACAO",
    "CYPRUS, NICOSIA",
    "CZECH REPUBLIC, PRAGUE",
    "DENMARK, COPENHAGEN",
    "DJIBOUTI, DJIBOUTI",
    "DOMINICAN REPUBLIC, SANTO DOMINGO",
    "ECUADOR, GUAYAQUIL",
    "ECUADOR, QUITO",
    "EGYPT, CAIRO",
    "EL SALVADOR, SAN SALVADOR",
    "ENGLAND, LONDON",
    "EQUATORIAL GUINEA, MALABO",
    "ERITREA, ASMARA",
    "ESTONIA, TALLINN",
    "ESWATINI, MBABANE",
    "ETHIOPIA, ADDIS ABABA",
    "FIJI, SUVA",
    "FINLAND, HELSINKI",
    "FRANCE, PARIS",
    "GABON, LIBREVILLE",
    "GAMBIA, BANJUL",
    "GEORGIA, TBILISI",
    "GERMANY, BERLIN",
    "GERMANY, FRANKFURT",
    "GERMANY, MUNICH",
    "GHANA, ACCRA",
    "GREECE, ATHENS",
    "GUATEMALA, GUATEMALA CITY",
    "GUINEA, CONAKRY",
    "GUYANA, GEORGETOWN",
    "HAITI, PORT-AU-PRINCE",
    "HONDURAS, TEGUCIGALPA",
    "HONG KONG",
    "HUNGARY, BUDAPEST",
    "ICELAND, REYKJAVIK",
    "INDIA, CHENNAI",
    "INDIA, HYDERABAD",
    "INDIA, KOLKATA",
    "INDIA, MUMBAI",
    "INDIA, NEW DELHI",
    "INDONESIA, JAKARTA",
    "INDONESIA, SURABAYA",
    "IRAQ, BAGHDAD",
    "IRAQ, ERBIL",
    "IRELAND, DUBLIN",
    "ISRAEL, TEL AVIV",
    "ITALY, FLORENCE",
    "ITALY, MILAN",
    "ITALY, NAPLES",
    "ITALY, ROME",
    "JAMAICA, KINGSTON",
    "JAPAN, NAHA",
    "JAPAN, OSAKA/FUKUOKA",
    "JAPAN, TOKYO/SAPPORO",
    "JERUSALEM",
    "JORDAN, AMMAN",
    "KAZAKHSTAN, ALMATY",
    "KAZAKHSTAN, ASTANA",
    "KENYA, NAIROBI",
    "KOSOVO, PRISTINA",
    "KUWAIT, KUWAIT CITY",
    "KYRGYZSTAN, BISHKEK",
    "LAOS, VIENTIANE",
    "LATVIA, RIGA",
    "LEBANON, BEIRUT",
    "LESOTHO, MASERU",
    "LIBERIA, MONROVIA",
    "LITHUANIA, VILNIUS",
    "LUXEMBOURG, LUXEMBOURG",
    "MACEDONIA, SKOPJE",
    "MADAGASCAR, ANTANANARIVO",
    "MALAWI, LILONGWE",
    "MALAYSIA, KUALA LUMPUR",
    "MALI, BAMAKO",
    "MALTA, VALLETTA",
    "MARSHALL ISLANDS, MAJURO",
    "MAURITANIA, NOUAKCHOTT",
    "MAURITIUS, PORT LOUIS",
    "MEXICO, CIUDAD JUAREZ",
    "MEXICO, GUADALAJARA",
    "MEXICO, HERMOSILLO",
    "MEXICO, MATAMOROS",
    "MEXICO, MERIDA",
    "MEXICO, MEXICO CITY",
    "MEXICO, MONTERREY",
    "MEXICO, NOGALES",
    "MEXICO, NUEVO LAREDO",
    "MEXICO, TIJUANA",
    "MICRONESIA, KOLONIA",
    "MOLDOVA, CHISINAU",
    "MONGOLIA, ULAANBAATAR",
    "MONTENEGRO, PODGORICA",
    "MOROCCO, CASABLANCA",
    "MOZAMBIQUE, MAPUTO",
    "NAMIBIA, WINDHOEK",
    "NEPAL, KATHMANDU",
    "NETHERLANDS, AMSTERDAM",
    "NEW ZEALAND, AUCKLAND",
    "NICARAGUA, MANAGUA",
    "NIGER, NIAMEY",
    "NIGERIA, ABUJA",
    "NIGERIA, LAGOS",
    "NORTHERN IRELAND, BELFAST",
    "NORWAY, OSLO",
    "OMAN, MUSCAT",
    "PAKISTAN, ISLAMABAD",
    "PAKISTAN, KARACHI",
    "PALAU, KOROR",
    "PANAMA, PANAMA CITY",
    "PAPUA NEW GUINEA, PORT MORESBY",
    "PARAGUAY, ASUNCION",
    "PERU, LIMA",
    "PHILIPPINES, MANILA",
    "POLAND, KRAKOW",
    "POLAND, WARSAW",
    "PORTUGAL, LISBON",
    "QATAR, DOHA",
    "ROMANIA, BUCHAREST",
    "RUSSIA, MOSCOW",
    "RUSSIA, VLADIVOSTOK",
    "RUSSIA, YEKATERINBURG",
    "RWANDA, KIGALI",
    "SAMOA, APIA",
    "SAUDI ARABIA, DHAHRAN",
    "SAUDI ARABIA, JEDDAH",
    "SAUDI ARABIA, RIYADH",
    "SENEGAL, DAKAR",
    "SERBIA, BELGRADE",
    "SIERRA LEONE, FREETOWN",
    "SINGAPORE, SINGAPORE",
    "SLOVAKIA, BRATISLAVA",
    "SLOVENIA, LJUBLJANA",
    "SOUTH AFRICA, CAPE TOWN",
    "SOUTH AFRICA, DURBAN",
    "SOUTH AFRICA, JOHANNESBURG",
    "SOUTH KOREA, SEOUL",
    "SOUTH SUDAN, JUBA",
    "SPAIN, MADRID",
    "SRI LANKA, COLOMBO",
    "SUDAN, KHARTOUM",
    "SURINAME, PARAMARIBO",
    "SWEDEN, STOCKHOLM",
    "SWITZERLAND, BERN",
    "TAIWAN, TAIPEI",
    "TAJIKISTAN, DUSHANBE",
    "TANZANIA, DAR ES SALAAM",
    "THAILAND, BANGKOK",
    "THAILAND, CHIANG MAI",
    "TIMOR LESTE, DILI",
    "TOGO, LOME",
    "TRINIDAD, PORT OF SPAIN",
    "TUNISIA, TUNIS",
    "TURKEY, ANKARA",
    "TURKEY, ISTANBUL",
    "TURKMENISTAN, ASHGABAT",
    "UGANDA, KAMPALA",
    "UKRAINE, KYIV",
    "UNITED ARAB EMIRATES, ABU DHABI",
    "UNITED ARAB EMIRATES, DUBAI",
    "URUGUAY, MONTEVIDEO",
    "UZBEKISTAN, TASHKENT",
    "VENEZUELA, CARACAS",
    "VIETNAM, HANOI",
    "VIETNAM, HO CHI MINH CITY",
    "ZAMBIA, LUSAKA",
    "ZIMBABWE, HARARE",
]

export const countries_regions_option_label_list = [
    "AFGHANISTAN",
    "ALBANIA",
    "ALGERIA",
    "AMERICAN SAMOA",
    "ANDORRA",
    "ANGOLA",
    "ANGUILLA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "ARUBA",
    "AT SEA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA",
    "BONAIRE",
    "BOSNIA-HERZEGOVINA",
    "BOTSWANA",
    "BRAZIL",
    "BRITISH INDIAN OCEAN TERRITORY",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "BURMA",
    "BURUNDI",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CABO VERDE",
    "CAYMAN ISLANDS",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHILE",
    "CHINA",
    "CHRISTMAS ISLAND",
    "COCOS KEELING ISLANDS",
    "COLOMBIA",
    "COMOROS",
    "CONGO, DEMOCRATIC REPUBLIC OF THE",
    "CONGO, REPUBLIC OF THE",
    "COOK ISLANDS",
    "COSTA RICA",
    "COTE D`IVOIRE",
    "CROATIA",
    "CUBA",
    "CURACAO",
    "CYPRUS",
    "CZECH REPUBLIC",
    "DENMARK",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESTONIA",
    "ESWATINI",
    "ETHIOPIA",
    "FALKLAND ISLANDS",
    "FAROE ISLANDS",
    "FIJI",
    "FINLAND",
    "FRANCE",
    "FRENCH GUIANA",
    "FRENCH POLYNESIA",
    "FRENCH SOUTHERN AND ANTARCTIC TERRITORIES",
    "GABON",
    "GAMBIA, THE",
    "GAZA STRIP",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GIBRALTAR",
    "GREECE",
    "GREENLAND",
    "GRENADA",
    "GUADELOUPE",
    "GUAM",
    "GUATEMALA",
    "GUINEA",
    "GUINEA - BISSAU",
    "GUYANA",
    "HAITI",
    "HEARD AND MCDONALD ISLANDS",
    "HOLY SEE (VATICAN CITY)",
    "HONDURAS",
    "HONG KONG BNO",
    "HONG KONG SAR",
    "HOWLAND ISLAND",
    "HUNGARY",
    "ICELAND",
    "IN THE AIR",
    "INDIA",
    "INDONESIA",
    "IRAN",
    "IRAQ",
    "IRELAND",
    "ISRAEL",
    "ITALY",
    "JAMAICA",
    "JAPAN",
    "JERUSALEM",
    "JORDAN",
    "KAZAKHSTAN",
    "KENYA",
    "KIRIBATI",
    "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)",
    "KOREA, REPUBLIC OF (SOUTH)",
    "KOSOVO",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAOS",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LUXEMBOURG",
    "MACAU",
    "MACEDONIA",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDEN ISLAND",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MARSHALL ISLANDS",
    "MARTINIQUE",
    "MAURITANIA",
    "MAURITIUS",
    "MAYOTTE",
    "MEXICO - AGUASCALIENTES",
    "MEXICO - BAJA CALIFORNIA NORTE",
    "MEXICO - BAJA CALIFORNIA SUR",
    "MEXICO - CAMPECHE",
    "MEXICO - CHIAPAS",
    "MEXICO - CHIHUAHUA",
    "MEXICO - COAHUILA",
    "MEXICO - COLIMA",
    "MEXICO - DISTRITO FEDERAL",
    "MEXICO - DURANGO",
    "MEXICO - GUANAJUATO",
    "MEXICO - GUERRERO",
    "MEXICO - HIDALGO",
    "MEXICO - JALISCO",
    "MEXICO - MICHOACAN",
    "MEXICO - MORELOS",
    "MEXICO - NAYARIT",
    "MEXICO - NUEVO LEON",
    "MEXICO - OAXACA",
    "MEXICO - PUEBLA",
    "MEXICO - QUERETARO",
    "MEXICO - QUINTANA ROO",
    "MEXICO - SAN LUIS POTOSI",
    "MEXICO - SINALOA",
    "MEXICO - SONORA",
    "MEXICO - STATE OF MEXICO",
    "MEXICO - TABASCO",
    "MEXICO - TAMAULIPAS",
    "MEXICO - TLAXCALA",
    "MEXICO - VERACRUZ",
    "MEXICO - YUCATAN",
    "MEXICO - ZACATECAS",
    "MICRONESIA",
    "MIDWAY ISLANDS",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MONTENEGRO",
    "MONTSERRAT",
    "MOROCCO",
    "MOZAMBIQUE",
    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NETHERLANDS",
    "NEW CALEDONIA",
    "NEW ZEALAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NIUE",
    "NORFOLK ISLAND",
    "NORTH MARIANA ISLANDS",
    "NORTHERN IRELAND",
    "NORWAY",
    "OMAN",
    "PAKISTAN",
    "PALAU",
    "PALMYRA ATOLL",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "PHILIPPINES",
    "PITCAIRN ISLANDS",
    "POLAND",
    "PORTUGAL",
    "PUERTO RICO",
    "QATAR",
    "REUNION",
    "ROMANIA",
    "RUSSIA",
    "RWANDA",
    "SABA ISLAND",
    "SAINT MARTIN",
    "SAMOA",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPORE",
    "SINT MAARTEN",
    "SLOVAKIA",
    "SLOVENIA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SOUTH AFRICA",
    "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND",
    "SOUTH SUDAN",
    "SPAIN",
    "SRI LANKA",
    "ST. BARTHELEMY",
    "ST. EUSTATIUS",
    "ST. HELENA",
    "ST. KITTS AND NEVIS",
    "ST. LUCIA",
    "ST. PIERRE AND MIQUELON",
    "ST. VINCENT AND THE GRENADINES",
    "SUDAN",
    "SURINAME",
    "SVALBARD",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIA",
    "TAIWAN",
    "TAJIKISTAN",
    "TANZANIA",
    "THAILAND",
    "TIMOR-LESTE",
    "TOGO",
    "TOKELAU",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "TURKS AND CAICOS ISLANDS",
    "TUVALU",
    "UGANDA",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED KINGDOM",
    "UNITED STATES OF AMERICA",
    "URUGUAY",
    "UZBEKISTAN",
    "VANUATU",
    "VENEZUELA",
    "VIETNAM",
    "VIRGIN ISLANDS (U.S.)",
    "VIRGIN ISLANDS, BRITISH",
    "WAKE ISLAND",
    "WALLIS AND FUTUNA ISLANDS",
    "WEST BANK",
    "WESTERN SAHARA",
    "YEMEN",
    "ZAMBIA",
    "ZIMBABWE",
]

export const countries_regions_option_value_list = [
    "AFGH",
    "ALB",
    "ALGR",
    "ASMO",
    "ANDO",
    "ANGL",
    "ANGU",
    "ANTI",
    "ARG",
    "ARM",
    "ARB",
    "XAS",
    "ASTL",
    "AUST",
    "AZR",
    "BAMA",
    "BAHR",
    "BANG",
    "BRDO",
    "BYS",
    "BELG",
    "BLZ",
    "BENN",
    "BERM",
    "BHU",
    "BOL",
    "BON",
    "BIH",
    "BOT",
    "BRZL",
    "IOT",
    "BRNI",
    "BULG",
    "BURK",
    "BURM",
    "BRND",
    "CBDA",
    "CMRN",
    "CAN",
    "CAVI",
    "CAYI",
    "CAFR",
    "CHAD",
    "CHIL",
    "CHIN",
    "CHRI",
    "COCI",
    "COL",
    "COMO",
    "COD",
    "CONB",
    "CKIS",
    "CSTR",
    "IVCO",
    "HRV",
    "CUBA",
    "CUR",
    "CYPR",
    "CZEC",
    "DEN",
    "DJI",
    "DOMN",
    "DOMR",
    "ECUA",
    "EGYP",
    "ELSL",
    "EGN",
    "ERI",
    "EST",
    "SZLD",
    "ETH",
    "FKLI",
    "FRO",
    "FIJI",
    "FIN",
    "FRAN",
    "FRGN",
    "FPOL",
    "FSAT",
    "GABN",
    "GAM",
    "XGZ",
    "GEO",
    "GER",
    "GHAN",
    "GIB",
    "GRC",
    "GRLD",
    "GREN",
    "GUAD",
    "GUAM",
    "GUAT",
    "GNEA",
    "GUIB",
    "GUY",
    "HAT",
    "HMD",
    "VAT",
    "HOND",
    "HOKO",
    "HNK",
    "XHI",
    "HUNG",
    "ICLD",
    "XIR",
    "IND",
    "IDSA",
    "IRAN",
    "IRAQ",
    "IRE",
    "ISRL",
    "ITLY",
    "JAM",
    "JPN",
    "JRSM",
    "JORD",
    "KAZ",
    "KENY",
    "KIRI",
    "PRK",
    "KOR",
    "KSV",
    "KUWT",
    "KGZ",
    "LAOS",
    "LATV",
    "LEBN",
    "LES",
    "LIBR",
    "LBYA",
    "LCHT",
    "LITH",
    "LXM",
    "MAC",
    "MKD",
    "MADG",
    "MALW",
    "MLAS",
    "MLDI",
    "MLDV",
    "MALI",
    "MLTA",
    "RMI",
    "MART",
    "MAUR",
    "MRTS",
    "MYT",
    "AGS",
    "BC",
    "BCSR",
    "CAMP",
    "CHIS",
    "CHIH",
    "COAH",
    "COLI",
    "DF",
    "DGO",
    "GTO",
    "GRO",
    "HGO",
    "JAL",
    "MCH",
    "MOR",
    "NAY",
    "NL",
    "OAX",
    "PUE",
    "QRO",
    "QROO",
    "SLP",
    "SIN",
    "SON",
    "MXCO",
    "TAB",
    "TAMP",
    "TLAX",
    "VER",
    "YUC",
    "ZAC",
    "FSM",
    "MDWI",
    "MLD",
    "MON",
    "MONG",
    "MTG",
    "MONT",
    "MORO",
    "MOZ",
    "NAMB",
    "NAU",
    "NEP",
    "NETH",
    "NCAL",
    "NZLD",
    "NIC",
    "NIR",
    "NRA",
    "NIUE",
    "NFK",
    "MNP",
    "NIRE",
    "NORW",
    "OMAN",
    "PKST",
    "PALA",
    "PLMR",
    "PAN",
    "PNG",
    "PARA",
    "PERU",
    "PHIL",
    "PITC",
    "POL",
    "PORT",
    "PR",
    "QTAR",
    "REUN",
    "ROM",
    "RUS",
    "RWND",
    "SABA",
    "MAF",
    "WSAM",
    "SMAR",
    "STPR",
    "SARB",
    "SENG",
    "SBA",
    "SEYC",
    "SLEO",
    "SING",
    "STM",
    "SVK",
    "SVN",
    "SLMN",
    "SOMA",
    "SAFR",
    "SGS",
    "SSDN",
    "SPN",
    "SRL",
    "STBR",
    "STEU",
    "SHEL",
    "STCN",
    "SLCA",
    "SPMI",
    "STVN",
    "SUDA",
    "SURM",
    "SJM",
    "SWDN",
    "SWTZ",
    "SYR",
    "TWAN",
    "TJK",
    "TAZN",
    "THAI",
    "TMOR",
    "TOGO",
    "TKL",
    "TONG",
    "TRIN",
    "TNSA",
    "TRKY",
    "TKM",
    "TCIS",
    "TUV",
    "UGAN",
    "UKR",
    "UAE",
    "GRBR",
    "USA",
    "URU",
    "UZB",
    "VANU",
    "VENZ",
    "VTNM",
    "VI",
    "BRVI",
    "WKI",
    "WAFT",
    "XWB",
    "SSAH",
    "YEM",
    "ZAMB",
    "ZIMB"
]


export const countries_only_option_label_list = [
    "AFGHANISTAN",
    "ALBANIA",
    "ALGERIA",
    "ANDORRA",
    "ANGOLA",
    "ANGUILLA",
    "ANTIGUA AND BARBUDA",
    "ARGENTINA",
    "ARMENIA",
    "AUSTRALIA",
    "AUSTRIA",
    "AZERBAIJAN",
    "BAHAMAS",
    "BAHRAIN",
    "BANGLADESH",
    "BARBADOS",
    "BELARUS",
    "BELGIUM",
    "BELIZE",
    "BENIN",
    "BERMUDA",
    "BHUTAN",
    "BOLIVIA",
    "BOSNIA-HERZEGOVINA",
    "BOTSWANA",
    "BRAZIL",
    "BRITISH INDIAN OCEAN TERRITORY",
    "BRUNEI",
    "BULGARIA",
    "BURKINA FASO",
    "BURMA",
    "BURUNDI",
    "CAMBODIA",
    "CAMEROON",
    "CANADA",
    "CABO VERDE",
    "CAYMAN ISLANDS",
    "CENTRAL AFRICAN REPUBLIC",
    "CHAD",
    "CHILE",
    "CHINA",
    "COLOMBIA",
    "COMOROS",
    "CONGO, DEMOCRATIC REPUBLIC OF THE",
    "CONGO, REPUBLIC OF THE",
    "COSTA RICA",
    "COTE D`IVOIRE",
    "CROATIA",
    "CUBA",
    "CYPRUS",
    "CZECH REPUBLIC",
    "DENMARK",
    "DJIBOUTI",
    "DOMINICA",
    "DOMINICAN REPUBLIC",
    "ECUADOR",
    "EGYPT",
    "EL SALVADOR",
    "EQUATORIAL GUINEA",
    "ERITREA",
    "ESTONIA",
    "ESWATINI",
    "ETHIOPIA",
    "FIJI",
    "FINLAND",
    "FRANCE",
    "GABON",
    "GAMBIA, THE",
    "GEORGIA",
    "GERMANY",
    "GHANA",
    "GIBRALTAR",
    "GREECE",
    "GRENADA",
    "GUATEMALA",
    "GUINEA",
    "GUINEA - BISSAU",
    "GUYANA",
    "HAITI",
    "HOLY SEE (VATICAN CITY)",
    "HONDURAS",
    "HONG KONG BNO",
    "HONG KONG SAR",
    "HUNGARY",
    "ICELAND",
    "INDIA",
    "INDONESIA",
    "IRAN",
    "IRAQ",
    "IRELAND",
    "ISRAEL",
    "ITALY",
    "JAMAICA",
    "JAPAN",
    "JORDAN",
    "KAZAKHSTAN",
    "KENYA",
    "KIRIBATI",
    "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)",
    "KOREA, REPUBLIC OF (SOUTH)",
    "KOSOVO",
    "KUWAIT",
    "KYRGYZSTAN",
    "LAOS",
    "LATVIA",
    "LEBANON",
    "LESOTHO",
    "LIBERIA",
    "LIBYA",
    "LIECHTENSTEIN",
    "LITHUANIA",
    "LUXEMBOURG",
    "MACAU",
    "MACEDONIA",
    "MADAGASCAR",
    "MALAWI",
    "MALAYSIA",
    "MALDIVES",
    "MALI",
    "MALTA",
    "MARSHALL ISLANDS",
    "MAURITANIA",
    "MAURITIUS",
    "MEXICO",
    "MICRONESIA",
    "MOLDOVA",
    "MONACO",
    "MONGOLIA",
    "MONTENEGRO",
    "MONTSERRAT",
    "MOROCCO",
    "MOZAMBIQUE",
    "NAMIBIA",
    "NAURU",
    "NEPAL",
    "NETHERLANDS",
    "NEW ZEALAND",
    "NICARAGUA",
    "NIGER",
    "NIGERIA",
    "NORWAY",
    "OMAN",
    "PAKISTAN",
    "PALAU",
    "PALESTINIAN AUTHORITY",
    "PANAMA",
    "PAPUA NEW GUINEA",
    "PARAGUAY",
    "PERU",
    "PHILIPPINES",
    "PITCAIRN ISLANDS",
    "POLAND",
    "PORTUGAL",
    "QATAR",
    "ROMANIA",
    "RUSSIA",
    "RWANDA",
    "SAMOA",
    "SAN MARINO",
    "SAO TOME AND PRINCIPE",
    "SAUDI ARABIA",
    "SENEGAL",
    "SERBIA",
    "SEYCHELLES",
    "SIERRA LEONE",
    "SINGAPORE",
    "SLOVAKIA",
    "SLOVENIA",
    "SOLOMON ISLANDS",
    "SOMALIA",
    "SOUTH AFRICA",
    "SOUTH SUDAN",
    "SPAIN",
    "SRI LANKA",
    "ST. HELENA",
    "ST. KITTS AND NEVIS",
    "ST. LUCIA",
    "ST. VINCENT AND THE GRENADINES",
    "STATELESS",
    "SUDAN",
    "SURINAME",
    "SWEDEN",
    "SWITZERLAND",
    "SYRIA",
    "TAIWAN",
    "TAJIKISTAN",
    "TANZANIA",
    "THAILAND",
    "TIMOR-LESTE",
    "TOGO",
    "TONGA",
    "TRINIDAD AND TOBAGO",
    "TUNISIA",
    "TURKEY",
    "TURKMENISTAN",
    "TURKS AND CAICOS ISLANDS",
    "TUVALU",
    "UGANDA",
    "UKRAINE",
    "UNITED ARAB EMIRATES",
    "UNITED KINGDOM",
    "URUGUAY",
    "UZBEKISTAN",
    "VANUATU",
    "VENEZUELA",
    "VIETNAM",
    "VIRGIN ISLANDS, BRITISH",
    "WALLIS AND FUTUNA ISLANDS",
    "WESTERN SAHARA",
    "YEMEN",
    "ZAMBIA",
    "ZIMBABWE",
];

export const countries_only_option_value_list = [
    "AFGH",
    "ALB",
    "ALGR",
    "ANDO",
    "ANGL",
    "ANGU",
    "ANTI",
    "ARG",
    "ARM",
    "ASTL",
    "AUST",
    "AZR",
    "BAMA",
    "BAHR",
    "BANG",
    "BRDO",
    "BYS",
    "BELG",
    "BLZ",
    "BENN",
    "BERM",
    "BHU",
    "BOL",
    "BIH",
    "BOT",
    "BRZL",
    "IOT",
    "BRNI",
    "BULG",
    "BURK",
    "BURM",
    "BRND",
    "CBDA",
    "CMRN",
    "CAN",
    "CAVI",
    "CAYI",
    "CAFR",
    "CHAD",
    "CHIL",
    "CHIN",
    "COL",
    "COMO",
    "COD",
    "CONB",
    "CSTR",
    "IVCO",
    "HRV",
    "CUBA",
    "CYPR",
    "CZEC",
    "DEN",
    "DJI",
    "DOMN",
    "DOMR",
    "ECUA",
    "EGYP",
    "ELSL",
    "EGN",
    "ERI",
    "EST",
    "SZLD",
    "ETH",
    "FIJI",
    "FIN",
    "FRAN",
    "GABN",
    "GAM",
    "GEO",
    "GER",
    "GHAN",
    "GIB",
    "GRC",
    "GREN",
    "GUAT",
    "GNEA",
    "GUIB",
    "GUY",
    "HAT",
    "VAT",
    "HOND",
    "HOKO",
    "HNK",
    "HUNG",
    "ICLD",
    "IND",
    "IDSA",
    "IRAN",
    "IRAQ",
    "IRE",
    "ISRL",
    "ITLY",
    "JAM",
    "JPN",
    "JORD",
    "KAZ",
    "KENY",
    "KIRI",
    "PRK",
    "KOR",
    "KSV",
    "KUWT",
    "KGZ",
    "LAOS",
    "LATV",
    "LEBN",
    "LES",
    "LIBR",
    "LBYA",
    "LCHT",
    "LITH",
    "LXM",
    "MAC",
    "MKD",
    "MADG",
    "MALW",
    "MLAS",
    "MLDV",
    "MALI",
    "MLTA",
    "RMI",
    "MAUR",
    "MRTS",
    "MEX",
    "FSM",
    "MLD",
    "MON",
    "MONG",
    "MTG",
    "MONT",
    "MORO",
    "MOZ",
    "NAMB",
    "NAU",
    "NEP",
    "NETH",
    "NZLD",
    "NIC",
    "NIR",
    "NRA",
    "NORW",
    "OMAN",
    "PKST",
    "PALA",
    "PAL",
    "PAN",
    "PNG",
    "PARA",
    "PERU",
    "PHIL",
    "PITC",
    "POL",
    "PORT",
    "QTAR",
    "ROM",
    "RUS",
    "RWND",
    "WSAM",
    "SMAR",
    "STPR",
    "SARB",
    "SENG",
    "SBA",
    "SEYC",
    "SLEO",
    "SING",
    "SVK",
    "SVN",
    "SLMN",
    "SOMA",
    "SAFR",
    "SSDN",
    "SPN",
    "SRL",
    "SHEL",
    "STCN",
    "SLCA",
    "STVN",
    "XXX",
    "SUDA",
    "SURM",
    "SWDN",
    "SWTZ",
    "SYR",
    "TWAN",
    "TJK",
    "TAZN",
    "THAI",
    "TMOR",
    "TOGO",
    "TONG",
    "TRIN",
    "TNSA",
    "TRKY",
    "TKM",
    "TCIS",
    "TUV",
    "UGAN",
    "UKR",
    "UAE",
    "GRBR",
    "URU",
    "UZB",
    "VANU",
    "VENZ",
    "VTNM",
    "BRVI",
    "WAFT",
    "SSAH",
    "YEM",
    "ZAMB",
    "ZIMB",
]

export const nationality_option_list = [
    <option value="AFGH">AFGHANISTAN</option>,
    <option value="ALB">ALBANIA</option>,
    <option value="ALGR">ALGERIA</option>,
    <option value="ANDO">ANDORRA</option>,
    <option value="ANGL">ANGOLA</option>,
    <option value="ANGU">ANGUILLA</option>,
    <option value="ANTI">ANTIGUA AND BARBUDA</option>,
    <option value="ARG">ARGENTINA</option>,
    <option value="ARM">ARMENIA</option>,
    <option value="ASTL">AUSTRALIA</option>,
    <option value="AUST">AUSTRIA</option>,
    <option value="AZR">AZERBAIJAN</option>,
    <option value="BAMA">BAHAMAS</option>,
    <option value="BAHR">BAHRAIN</option>,
    <option value="BANG">BANGLADESH</option>,
    <option value="BRDO">BARBADOS</option>,
    <option value="BYS">BELARUS</option>,
    <option value="BELG">BELGIUM</option>,
    <option value="BLZ">BELIZE</option>,
    <option value="BENN">BENIN</option>,
    <option value="BERM">BERMUDA</option>,
    <option value="BHU">BHUTAN</option>,
    <option value="BOL">BOLIVIA</option>,
    <option value="BIH">BOSNIA-HERZEGOVINA</option>,
    <option value="BOT">BOTSWANA</option>,
    <option value="BRZL">BRAZIL</option>,
    <option value="IOT">BRITISH INDIAN OCEAN TERRITORY</option>,
    <option value="BRNI">BRUNEI</option>,
    <option value="BULG">BULGARIA</option>,
    <option value="BURK">BURKINA FASO</option>,
    <option value="BURM">BURMA</option>,
    <option value="BRND">BURUNDI</option>,
    <option value="CBDA">CAMBODIA</option>,
    <option value="CMRN">CAMEROON</option>,
    <option value="CAN">CANADA</option>,
    <option value="CAVI">CABO VERDE</option>,
    <option value="CAYI">CAYMAN ISLANDS</option>,
    <option value="CAFR">CENTRAL AFRICAN REPUBLIC</option>,
    <option value="CHAD">CHAD</option>,
    <option value="CHIL">CHILE</option>,
    <option value="CHIN">CHINA</option>,
    <option value="COL">COLOMBIA</option>,
    <option value="COMO">COMOROS</option>,
    <option value="COD">CONGO, DEMOCRATIC REPUBLIC OF THE</option>,
    <option value="CONB">CONGO, REPUBLIC OF THE</option>,
    <option value="CSTR">COSTA RICA</option>,
    <option value="IVCO">COTE D`IVOIRE</option>,
    <option value="HRV">CROATIA</option>,
    <option value="CUBA">CUBA</option>,
    <option value="CYPR">CYPRUS</option>,
    <option value="CZEC">CZECH REPUBLIC</option>,
    <option value="DEN">DENMARK</option>,
    <option value="DJI">DJIBOUTI</option>,
    <option value="DOMN">DOMINICA</option>,
    <option value="DOMR">DOMINICAN REPUBLIC</option>,
    <option value="ECUA">ECUADOR</option>,
    <option value="EGYP">EGYPT</option>,
    <option value="ELSL">EL SALVADOR</option>,
    <option value="EGN">EQUATORIAL GUINEA</option>,
    <option value="ERI">ERITREA</option>,
    <option value="EST">ESTONIA</option>,
    <option value="SZLD">ESWATINI</option>,
    <option value="ETH">ETHIOPIA</option>,
    <option value="FIJI">FIJI</option>,
    <option value="FIN">FINLAND</option>,
    <option value="FRAN">FRANCE</option>,
    <option value="GABN">GABON</option>,
    <option value="GAM">GAMBIA, THE</option>,
    <option value="GEO">GEORGIA</option>,
    <option value="GER">GERMANY</option>,
    <option value="GHAN">GHANA</option>,
    <option value="GIB">GIBRALTAR</option>,
    <option value="GRC">GREECE</option>,
    <option value="GREN">GRENADA</option>,
    <option value="GUAT">GUATEMALA</option>,
    <option value="GNEA">GUINEA</option>,
    <option value="GUIB">GUINEA - BISSAU</option>,
    <option value="GUY">GUYANA</option>,
    <option value="HAT">HAITI</option>,
    <option value="VAT">HOLY SEE (VATICAN CITY)</option>,
    <option value="HOND">HONDURAS</option>,
    <option value="HOKO">HONG KONG BNO</option>,
    <option value="HNK">HONG KONG SAR</option>,
    <option value="HUNG">HUNGARY</option>,
    <option value="ICLD">ICELAND</option>,
    <option value="IND">INDIA</option>,
    <option value="IDSA">INDONESIA</option>,
    <option value="IRAN">IRAN</option>,
    <option value="IRAQ">IRAQ</option>,
    <option value="IRE">IRELAND</option>,
    <option value="ISRL">ISRAEL</option>,
    <option value="ITLY">ITALY</option>,
    <option value="JAM">JAMAICA</option>,
    <option value="JPN">JAPAN</option>,
    <option value="JORD">JORDAN</option>,
    <option value="KAZ">KAZAKHSTAN</option>,
    <option value="KENY">KENYA</option>,
    <option value="KIRI">KIRIBATI</option>,
    <option value="PRK">KOREA, DEMOCRATIC REPUBLIC OF (NORTH)</option>,
    <option value="KOR">KOREA, REPUBLIC OF (SOUTH)</option>,
    <option value="KSV">KOSOVO</option>,
    <option value="KUWT">KUWAIT</option>,
    <option value="KGZ">KYRGYZSTAN</option>,
    <option value="LAOS">LAOS</option>,
    <option value="LATV">LATVIA</option>,
    <option value="LEBN">LEBANON</option>,
    <option value="LES">LESOTHO</option>,
    <option value="LIBR">LIBERIA</option>,
    <option value="LBYA">LIBYA</option>,
    <option value="LCHT">LIECHTENSTEIN</option>,
    <option value="LITH">LITHUANIA</option>,
    <option value="LXM">LUXEMBOURG</option>,
    <option value="MAC">MACAU</option>,
    <option value="MKD">MACEDONIA</option>,
    <option value="MADG">MADAGASCAR</option>,
    <option value="MALW">MALAWI</option>,
    <option value="MLAS">MALAYSIA</option>,
    <option value="MLDV">MALDIVES</option>,
    <option value="MALI">MALI</option>,
    <option value="MLTA">MALTA</option>,
    <option value="RMI">MARSHALL ISLANDS</option>,
    <option value="MAUR">MAURITANIA</option>,
    <option value="MRTS">MAURITIUS</option>,
    <option value="MEX">MEXICO</option>,
    <option value="FSM">MICRONESIA</option>,
    <option value="MLD">MOLDOVA</option>,
    <option value="MON">MONACO</option>,
    <option value="MONG">MONGOLIA</option>,
    <option value="MTG">MONTENEGRO</option>,
    <option value="MONT">MONTSERRAT</option>,
    <option value="MORO">MOROCCO</option>,
    <option value="MOZ">MOZAMBIQUE</option>,
    <option value="NAMB">NAMIBIA</option>,
    <option value="NAU">NAURU</option>,
    <option value="NEP">NEPAL</option>,
    <option value="NETH">NETHERLANDS</option>,
    <option value="NZLD">NEW ZEALAND</option>,
    <option value="NIC">NICARAGUA</option>,
    <option value="NIR">NIGER</option>,
    <option value="NRA">NIGERIA</option>,
    <option value="NORW">NORWAY</option>,
    <option value="OMAN">OMAN</option>,
    <option value="PKST">PAKISTAN</option>,
    <option value="PALA">PALAU</option>,
    <option value="PAL">PALESTINIAN AUTHORITY</option>,
    <option value="PAN">PANAMA</option>,
    <option value="PNG">PAPUA NEW GUINEA</option>,
    <option value="PARA">PARAGUAY</option>,
    <option value="PERU">PERU</option>,
    <option value="PHIL">PHILIPPINES</option>,
    <option value="PITC">PITCAIRN ISLANDS</option>,
    <option value="POL">POLAND</option>,
    <option value="PORT">PORTUGAL</option>,
    <option value="QTAR">QATAR</option>,
    <option value="ROM">ROMANIA</option>,
    <option value="RUS">RUSSIA</option>,
    <option value="RWND">RWANDA</option>,
    <option value="WSAM">SAMOA</option>,
    <option value="SMAR">SAN MARINO</option>,
    <option value="STPR">SAO TOME AND PRINCIPE</option>,
    <option value="SARB">SAUDI ARABIA</option>,
    <option value="SENG">SENEGAL</option>,
    <option value="SBA">SERBIA</option>,
    <option value="SEYC">SEYCHELLES</option>,
    <option value="SLEO">SIERRA LEONE</option>,
    <option value="SING">SINGAPORE</option>,
    <option value="SVK">SLOVAKIA</option>,
    <option value="SVN">SLOVENIA</option>,
    <option value="SLMN">SOLOMON ISLANDS</option>,
    <option value="SOMA">SOMALIA</option>,
    <option value="SAFR">SOUTH AFRICA</option>,
    <option value="SSDN">SOUTH SUDAN</option>,
    <option value="SPN">SPAIN</option>,
    <option value="SRL">SRI LANKA</option>,
    <option value="SHEL">ST. HELENA</option>,
    <option value="STCN">ST. KITTS AND NEVIS</option>,
    <option value="SLCA">ST. LUCIA</option>,
    <option value="STVN">ST. VINCENT AND THE GRENADINES</option>,
    <option value="XXX">STATELESS</option>,
    <option value="SUDA">SUDAN</option>,
    <option value="SURM">SURINAME</option>,
    <option value="SWDN">SWEDEN</option>,
    <option value="SWTZ">SWITZERLAND</option>,
    <option value="SYR">SYRIA</option>,
    <option value="TWAN">TAIWAN</option>,
    <option value="TJK">TAJIKISTAN</option>,
    <option value="TAZN">TANZANIA</option>,
    <option value="THAI">THAILAND</option>,
    <option value="TMOR">TIMOR-LESTE</option>,
    <option value="TOGO">TOGO</option>,
    <option value="TONG">TONGA</option>,
    <option value="TRIN">TRINIDAD AND TOBAGO</option>,
    <option value="TNSA">TUNISIA</option>,
    <option value="TRKY">TURKEY</option>,
    <option value="TKM">TURKMENISTAN</option>,
    <option value="TCIS">TURKS AND CAICOS ISLANDS</option>,
    <option value="TUV">TUVALU</option>,
    <option value="UGAN">UGANDA</option>,
    <option value="UKR">UKRAINE</option>,
    <option value="UAE">UNITED ARAB EMIRATES</option>,
    <option value="GRBR">UNITED KINGDOM</option>,
    <option value="URU">URUGUAY</option>,
    <option value="UZB">UZBEKISTAN</option>,
    <option value="VANU">VANUATU</option>,
    <option value="VENZ">VENEZUELA</option>,
    <option value="VTNM">VIETNAM</option>,
    <option value="BRVI">VIRGIN ISLANDS, BRITISH</option>,
    <option value="WAFT">WALLIS AND FUTUNA ISLANDS</option>,
    <option value="SSAH">WESTERN SAHARA</option>,
    <option value="YEM">YEMEN</option>,
    <option value="ZAMB">ZAMBIA</option>,
    <option value="ZIMB">ZIMBABWE</option>,
]